### ISSUE TITLE
imgui.Image() example

### ISSUE THREAD

**Issue by fourst4r** [gabstv/ebiten-imgui#7]
Hey, thanks for making this library, it's been extremely useful for me! Just wondering if you had any examples for using `imgui.Image` with ebiten?

**Comment by gabstv** [comment]
Hi! I didn't try using `imbui.Image` yet with Ebiten. I'll look it up on the weekend. Thanks for using this lib!

**Comment by gabstv** [comment]
https://github.com/gabstv/ebiten-imgui/blob/master/examples/images/main.go#L26
https://github.com/gabstv/ebiten-imgui/blob/master/examples/images/main.go#L44

**Comment by fourst4r** [comment]
Thanks a million!
